create table public.credit_balances (
  user_id uuid primary key references auth.users(id) on delete cascade,
  subscription_credits bigint not null default 0,
  topup_credits bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.credit_balances enable row level security;

create policy "Users can view their own credit balance"
on public.credit_balances
for select
to authenticated
using (auth.uid() = user_id);

create table public.credit_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null check (bucket in ('subscription', 'topup')),
  amount bigint not null,
  reason text not null,
  stripe_event_id text unique,
  created_at timestamptz not null default now()
);

alter table public.credit_transactions enable row level security;

create policy "Users can view their own credit transactions"
on public.credit_transactions
for select
to authenticated
using (auth.uid() = user_id);